### ISSUE TITLE
When whitelists are length 0, anyone can be recipient and/or donor?

### ISSUE THREAD

**Issue by asood123** [AllForClimate/matchingcryptofund#2]
This code makes me think that if whitelists were zero length, then anyone could be recipient and/or donor. Is that intentional? 

https://github.com/AllForClimate/matchingcryptofund/blob/6f3180abb7705e10712566b42a3a513292cbb79a/contracts/MatchingFund.sol#L162

**Comment by xdamman** [comment]
It's intentional on the donors side (anyone should be able to donate) but maybe we should enforce at least one whitelisted recipient.

Another feature I was thinking of is to whitelist automatically all the addresses that do have a certain token/NFT. 
This would make it super easy to create a matching fund to double donations made by people of a giving community.

Djeez, I realized this comment was already 25 days ago. It's hard to block time to properly focus on this. So much still needs to be built for this new crypto world!
